export enum DictNameEnums {
  LABEL_POSITION = "LABEL_POSITION",
  FORM_FIELD_TYPE = "FORM_FIELD_TYPE",
  TABLE_FIELD_TYPE = "TABLE_FIELD_TYPE",
  TABLE_FIELD_ALIGN = "TABLE_FIELD_ALIGN",
  UI_SIZE = "UI_SIZE"
}
