export enum DictNameEnum {
  ROLE_REL_TYPE = "ROLE_REL_TYPE",
  USE_STATE = "USE_STATE",
  LABEL_POSITION = "LABEL_POSITION",
  FORM_FIELD_TYPE = "FORM_FIELD_TYPE",
  TABLE_FIELD_TYPE = "TABLE_FIELD_TYPE",
  TABLE_FIELD_ALIGN = "TABLE_FIELD_ALIGN",
  UI_SIZE = "UI_SIZE",
  BOOLEAN = "BOOLEAN"
}
